let a , b , c ;
a = 5;
b = 6;
c = 7;
function minhafuncao(){
    document.write(a + b);
    document.write(a + c);
    document.write(b + c);
    document.write(a + b + c);
}
console.log(10+10*(a + b + c));
console.log('Matheus Paizante');
// Inserindo um texto no paragrafo :p
document.getElementById('texto1').innerHTML = `O valor de {a} + {b} é igual a {a+b}`

/*
var = nunca use
let = use para variaveis que podem mudar
const = use para variaves que nunca mudão 
*/ 
const pote = "bombom";
//alert(pote);
let a1 = 2;
let b1 = 3;
let c1 = a1 + b2;
alert(c1);

